### ISSUE TITLE
Attempted to read or write protected memory. 

### ISSUE THREAD

**Issue by lunamrcc** [SWI-Prolog/contrib-swiplcs#6]
Hello,

I have the following error:

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

I've seen many of the forums and many answers but I can't make it work... (Changing the name of the SwiPlCs64 to SwiPlCs dll, using SWI_HOME_DIR...)

This is my configuration:
SWI-Prolog (threaded, 32 bits, version 7.6.4)
SwiPlCs 1.1.60605.0
Visual Studio 17 15.7.5
.Net Framework 4.7.03056
Windows 10

**Comment by lunamrcc** [comment]
I figure it out:
The lastest version of SWI-Prolog don't work with SwiPlCs. I install  SWI-Prolog 6.6.1 (32 bits) and It work fine.

**Comment by MateuszChilinski** [comment]
Hey guys,

I've really struggled with problems with this packet, yet after hours of trying I figured out how to get it running on Win10 & newest Visual Studio, the complete guide to fixing the issue of this thread and also "The specified module could not be found. (Exception from HRESULT: 0x8007007E)" errors:

- use newest .dlls, if you have problems - change name of SwiPlCs64 to SwiPlCs and then add it to references
- you have to get SWI-Prolog with version MAX 7.4.2 (http://www.swi-prolog.org/download/stable?show=all) - otherwise it will not work. Also versions below 6.something might not work, 7.4.2 as the highest-stable I could run seems fine.
- you need to include prolog dlls in Window's %path% - it's either by default C:\Program Files\swipl or C:\Program Files\swipl\bin, I didn't check which because I just put both of them :)

Then it will start to work. @UweLesta it would be nice if you included it in readme but I don't know how active you are :) Thought great work with the project!

I'm pretty much writing it so it indexes on google and it will be easier to use for others who wish to use prolog in C# :)

**Comment by JanWielemaker** [comment]
This package is old.  It probably doesn't need much work as the C API of SWI-Prolog is pretty stable.  There have been a couple of versions that introduced __binary__ incompatibility.    Recompiling should fix that.  Also the name of the SWI-Prolog dll has changed a couple of times, as well as its dependencies.
